[package]
name = "pgstac-test"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
tokio-postgres = { version = "0.7" }
